### ISSUE TITLE
excercise  

### ISSUE THREAD

**Issue by darthvader365** [ismaelsadeghicode/OOP#2]
In the package miner create a class called MinerCollection. A MinerCollection stores all miners available for the user. Available miners are loaded at startup of the application. There should be only one instance of this class at any given time; implement code to enforce this.
In order to get a list of available classes, you can copy the following code:
```
List<File> minerFiles = new ArrayList<File>();
final String[] SUFFIX = {"class"};  // use the suffix to filter
File minerPath = Settings.instance().getMinerPath();
Collection<File> files = FileUtils.listFiles(minerPath, SUFFIX, true);
for (File file: files) {
	if ((file.getName().endsWith("Miner.class")) && 
(!file.getName().startsWith("I")) && 
(!file.getName().contains("Abstract"))) {
	    	minerFiles.add(file);
	}

```
This code will not check whether the classes found are actually valid miners functioning correctly! For now, add code to create an object of the class and print all available miners to the console at application startup.
This part of the assignment is worth 1 point.

**Comment by ismaelsadeghicode** [comment]
create a MinerCollection (singleton pattern). ismael
print to console. iman
